WebApplication1/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;
using X.PagedList;


namespace WebApplication1.Controllers
{
    public class PeopleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PeopleController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: People
        public async Task<IActionResult> Index(int? page, string sortOrder)
        {
            const int pageSize = 10;

            var applicationDbContext = _context.Person.Include(p => p.BirthPlace).Include(p => p.RegistrationPlace).AsQueryable();

            ViewData["DefaultSort"] = sortOrder;

            var people = from p in _context.Person select p;

            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "PersonName_desc" : "";
            ViewData["SurnameSortParm"] = sortOrder == "PersonSurname" ? "PersonSurname_desc" : "PersonSurname";
            ViewData["DateOfBirthSortParm"] = sortOrder == "PersonDateOfBirth" ? "PersonDateOfBirth_desc" : "PersonDateOfBirth";
            ViewData["RNKNumberSortParm"] = sortOrder == "RNKNumber" ? "RNKNumber_desc" : "RNKNumber";
            ViewData["PersonPassportIdSortParm"] = sortOrder == "PersonPassportId" ? "PersonPassportId_desc" : "PersonPassportId";

            var sortedPeople = SortPeople(people, sortOrder);

            int pageNumber = page ?? 1;
            var pagedModel = await sortedPeople.ToPagedListAsync(pageNumber, pageSize);

            return View(pagedModel);
        }


        private IQueryable<Person> SortPeople(IQueryable<Person> people, string sortOrder)
        {
            if (string.IsNullOrWhiteSpace(sortOrder))
            {
                return people.OrderBy(p => p.PersonName);
            }

            var descending = sortOrder.EndsWith("_desc");
            var propertyName = descending ? sortOrder[..^5] : sortOrder;

            switch (propertyName)
            {
                case "PersonName":
                    return descending ? people.OrderByDescending(p => p.PersonName) : people.OrderBy(p => p.PersonName);
                case "PersonSurname":
                    return descending ? people.OrderByDescending(p => p.PersonSurname) : people.OrderBy(p => p.PersonSurname);
                case "PersonDateOfBirth":
                    return descending ? people.OrderByDescending(p => p.PersonDateOfBirth) : people.OrderBy(p => p.PersonDateOfBirth);
                case "RNKNumber":
                    return descending ? people.OrderByDescending(p => p.RNKNumber) : people.OrderBy(p => p.RNKNumber);
                case "PersonPassportId":
                    return descending ? people.OrderByDescending(p => p.PersonPassportId) : people.OrderBy(p => p.PersonPassportId);
                default:
                    return people.OrderBy(p => p.PersonName);
            }
        }





        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .Include(p => p.RegistrationPlace)
                .Include(p => p.BirthPlace)
                .Include(p => p.PersonPassport)
                .FirstOrDefaultAsync(m => m.PersonId == id);

            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonId,PersonName,PersonSurname,PersonSex,PersonDateOfBirth,PersonNationality,RNKNumber,RegistrationPlaceId,BirthPlaceId,PersonPassportId")] Person person)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Check if person has a registration place
                    if (person.RegistrationPlace == null)
                    {
                        person.RegistrationPlace = new RegistrationPlaces();
                        _context.RegistrationPlaces.Add(person.RegistrationPlace);
                        await _context.SaveChangesAsync();
                    }

                    // Check if the person has a birth place
                    if (person.BirthPlace == null)
                    {
                        person.BirthPlace = new PlacesOfBirth();
                        _context.PlacesOfBirth.Add(person.BirthPlace);
                        await _context.SaveChangesAsync();
                    }

                    //Add person to the db
                    _context.Person.Add(person);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error creating the record. Please contact the administrator." + ex;
            }

            ViewBag.ErrorMessage = TempData["ErrorMessage"];

            return View("Create", person);
        }



        // POST: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var person = await _context.Person.FindAsync(id);
                if (person == null)
                {
                    return NotFound();
                }

                person.BirthPlace = await _context.PlacesOfBirth.FindAsync(person.BirthPlaceId);
                person.RegistrationPlace = await _context.RegistrationPlaces.FindAsync(person.RegistrationPlaceId);

                ViewData["BirthPlaceId"] = new SelectList(_context.PlacesOfBirth, "BirthPlaceId", "BirthPlaceId", person.BirthPlaceId);
                ViewData["RegistrationPlaceId"] = new SelectList(_context.RegistrationPlaces, "RegistrationPlaceId", "RegistrationPlaceId", person.RegistrationPlaceId);
                return View(person);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while trying to fetch the person for editing. Please try again." + ex);

                return RedirectToAction();
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            try
            {
                var person = await _context.Person
                    .Include(p => p.BirthPlace)
                    .Include(p => p.RegistrationPlace)
                    .FirstOrDefaultAsync(m => m.PersonId == id);

                if (person == null)
                {
                    return NotFound();
                }

                if (await TryUpdateModelAsync(person, "",
                    p => p.PersonName, p => p.PersonSurname, p => p.PersonSex,
                    p => p.PersonDateOfBirth, p => p.PersonNationality, p => p.RNKNumber,
                    p => p.RegistrationPlace, p => p.BirthPlace, p => p.PersonPassportId))
                {
                    _context.RegistrationPlaces.Update(person.RegistrationPlace);
                    _context.PlacesOfBirth.Update(person.BirthPlace);

                    _context.Person.Update(person);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }

                ViewData["BirthPlaceId"] = new SelectList(_context.PlacesOfBirth, "BirthPlaceId", "City", person.BirthPlaceId);
                ViewData["RegistrationPlaceId"] = new SelectList(_context.RegistrationPlaces, "RegistrationPlaceId", "City", person.RegistrationPlaceId);
                return View(person);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while trying to update the person. Please try again.");

                return RedirectToAction();
            }
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .Include(p => p.BirthPlace)
                .Include(p => p.RegistrationPlace)
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var person = await _context.Person
                    .Include(p => p.PersonPassport) 
                    .FirstOrDefaultAsync(m => m.PersonId == id);

                if (person == null)
                {
                    return NotFound();
                }

                if (person.PersonPassport != null)
                {
                    _context.PersonPassports.Remove(person.PersonPassport);
                }

                _context.Person.Remove(person);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error while deleting the person";
                return RedirectToAction(nameof(Index));
            }
        }


        private bool PersonExists(int id)
        {

WebApplication1/Controllers/PersonPassportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PersonPassportsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PersonPassportsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PersonPassports
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.PersonPassports.Include(p => p.Person);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: PersonPassports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personPassports = await _context.PersonPassports
                .Include(p => p.Person)
                .FirstOrDefaultAsync(m => m.PersonPassportId == id);
            if (personPassports == null)
            {
                return NotFound();
            }

            return View(personPassports);
        }

        // GET: PersonPassports/Create
        public IActionResult Create(int? personId, string returnUrl)
        {
            ViewData["PersonId"] = personId;
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonPassportId,Passport_Number,Passport_Type,Authority,Date_of_Issue,Date_of_Expiry,PersonId")] PersonPassports personPassports, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personPassports);
                await _context.SaveChangesAsync();

                int createdPassportId = personPassports.PersonPassportId ?? 0;

                var person = await _context.Person.FindAsync(personPassports.PersonId);

                if (person == null)
                {
                    ModelState.AddModelError("PersonId", "Invalid person ID.");
                    ViewData["PersonId"] = new SelectList(_context.Person, "PersonId", "PersonId", personPassports.PersonId);
                    return View(personPassports);
                }

                person.PersonPassportId = createdPassportId;
                _context.Update(person);
                await _context.SaveChangesAsync();

                return Redirect(returnUrl);
            }

            ViewData["PersonId"] = new SelectList(_context.Person, "PersonId", "PersonId", personPassports.PersonId);
            return View(personPassports);
        }


        // GET: PersonPassports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personPassports = await _context.PersonPassports.FindAsync(id);
            if (personPassports == null)
            {
                return NotFound();
            }
            ViewData["PersonId"] = new SelectList(_context.Person, "PersonId", "PersonId", personPassports.PersonId);
            return View(personPassports);
        }

        // POST: PersonPassports/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("PersonPassportId,Passport_Number,Passport_Type,Authority,Date_of_Issue,Date_of_Expiry,PersonId")] PersonPassports personPassports)
        {
            if (id != personPassports.PersonPassportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personPassports);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonPassportsExists(personPassports.PersonPassportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PersonId"] = new SelectList(_context.Person, "PersonId", "PersonId", personPassports.PersonId);
            return View(personPassports);
        }

        // GET: PersonPassports/Delete/5
        public async Task<IActionResult> Delete(int? id, string returnUrl)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personPassports = await _context.PersonPassports
                .Include(p => p.Person)
                .FirstOrDefaultAsync(m => m.PersonPassportId == id);

            if (personPassports == null)
            {
                return NotFound();
            }

            ViewData["PersonId"] = personPassports.PersonId;
            ViewData["ReturnUrl"] = returnUrl;
            return View(personPassports);
        }



        // POST: PersonPassports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id, string returnUrl)
        {
            var personPassports = await _context.PersonPassports.FindAsync(id);
            var person = await _context.Person.FindAsync(personPassports.PersonId);
            person.PersonPassportId = null;

            if (personPassports != null)
            {
                _context.PersonPassports.Remove(personPassports);
                await _context.SaveChangesAsync();
            }

            if (!string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Details", "People", new { id = personPassports.PersonId });
            }
        }




        private bool PersonPassportsExists(int? id)
        {
            return _context.PersonPassports.Any(e => e.PersonPassportId == id);
        }
    }
}

WebApplication1/Views/People/Create.cshtml
@model WebApplication1.Models.Person

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center d-inline-block">Create</h1>

<h4 class="text-center d-inline-block">Person</h4>
<hr />
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form  class="shadow p-3 mb-5 bg-white rounded" asp-action="Create">

            <div class="row">
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonName" class="control-label"></label>
                    <input asp-for="PersonName" class="form-control" />
                    <span asp-validation-for="PersonName" class="text-danger"></span>
                </div>
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonSurname" class="control-label"></label>
                    <input asp-for="PersonSurname" class="form-control" />
                    <span asp-validation-for="PersonSurname" class="text-danger"></span>
                </div>
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonSex" class="control-label"></label>

                    <div class="form-check">
                        <input type="radio" asp-for="PersonSex" class="form-check-input" value="Male" />
                        <label class="form-check-label">Male</label>
                    </div>

                    <div class="form-check">
                        <input type="radio" asp-for="PersonSex" class="form-check-input" value="Female" />
                        <label class="form-check-label">Female</label>
                    </div>

                    <span asp-validation-for="PersonSex" class="text-danger"></span>
                </div>

                <div class="col-md-6 mb-4">
                    <label asp-for="PersonDateOfBirth" class="control-label"></label>
                    <input asp-for="PersonDateOfBirth" class="form-control" type="date" />
                    <span asp-validation-for="PersonDateOfBirth" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonNationality" class="control-label"></label>
                    <input asp-for="PersonNationality" class="form-control" />
                    <span asp-validation-for="PersonNationality" class="text-danger"></span>
                </div>
                <div class="col-md-6 mb-4">
                    <label asp-for="RNKNumber" class="control-label"></label>
                    <input asp-for="RNKNumber" class="form-control" />
                    <span asp-validation-for="RNKNumber" class="text-danger"></span>
                </div>

            </div>

            <hr />
            <div class="row">
                <div class="col-md-4 mb-4">
                    <label asp-for="RegistrationPlace.Country" class="control-label">Registration Country</label>
                    <input asp-for="RegistrationPlace.Country" class="form-control" />
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="RegistrationPlace.Region" class="control-label">Registration Region</label>
                    <input asp-for="RegistrationPlace.Region" class="form-control" />
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="RegistrationPlace.City" class="control-label">Registration City</label>
                    <input asp-for="RegistrationPlace.City" class="form-control" />
                </div>

                <div class="col-md-4 mb-4">
                    <label asp-for="BirthPlace.Country" class="control-label">Birth Country</label>
                    <input asp-for="BirthPlace.Country" class="form-control" />
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="BirthPlace.Region" class="control-label">Birth Region</label>
                    <input asp-for="BirthPlace.Region" class="form-control" />
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="BirthPlace.City" class="control-label">Birth City</label>
                    <input asp-for="BirthPlace.City" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Create</button>
                <a asp-action="Index" asp-controller="People" class="btn btn-secondary">Back to List</a>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/People/Delete.cshtml
@model WebApplication1.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonSurname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonSurname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonSex)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonSex)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonDateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonDateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonNationality)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonNationality)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RNKNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RNKNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationPlace)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationPlace.RegistrationPlaceId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthPlace)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthPlace.BirthPlaceId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonPassportId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonPassportId)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="PersonId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

WebApplication1/Views/People/Details.cshtml
@model WebApplication1.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center d-inline-block">Details</h1>

<h4 class="text-center d-inline-block">Person</h4>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <form asp-action="Edit" class="shadow p-3 mb-5 bg-white rounded">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonId" />

            <div class="row">
                <!-- Column 1 -->
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonName" class="control-label"></label>
                    <input asp-for="PersonName" class="form-control" readonly />
                </div>
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonSurname" class="control-label"></label>
                    <input asp-for="PersonSurname" class="form-control" readonly />
                </div>
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonSex" class="control-label"></label>

                    <div class="form-check">
                        <input type="radio" asp-for="PersonSex" class="form-check-input" value="Male" disabled />
                        <label class="form-check-label">Male</label>
                    </div>

                    <div class="form-check">
                        <input type="radio" asp-for="PersonSex" class="form-check-input" value="Female" disabled />
                        <label class="form-check-label">Female</label>
                    </div>
                </div>

                <div class="col-md-6 mb-4">
                    <label asp-for="PersonDateOfBirth" class="control-label"></label>
                    <input asp-for="PersonDateOfBirth" class="form-control" type="date" readonly />
                </div>
            </div>

            <!-- Column 2 -->
            <div class="row">
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonNationality" class="control-label"></label>
                    <input asp-for="PersonNationality" class="form-control" readonly />
                </div>
                <div class="col-md-6 mb-4">
                    <label asp-for="RNKNumber" class="control-label"></label>
                    <input asp-for="RNKNumber" class="form-control" readonly />
                </div>
            </div>

           <hr />
            <!-- Registration Place -->
            <div class="row">
                <div class="col-md-4 mb-4">
                    <label asp-for="RegistrationPlace.Country" class="control-label">Registration Country</label>
                    <input asp-for="RegistrationPlace.Country" class="form-control" readonly />
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="RegistrationPlace.Region" class="control-label">Registration Region</label>
                    <input asp-for="RegistrationPlace.Region" class="form-control" readonly />
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="RegistrationPlace.City" class="control-label">Registration City</label>
                    <input asp-for="RegistrationPlace.City" class="form-control" readonly />
                </div>
            </div>

            <!-- Birth Place -->
            <div class="row">
                <div class="col-md-4 mb-4">
                    <label asp-for="BirthPlace.Country" class="control-label">Birth Country</label>
                    <input asp-for="BirthPlace.Country" class="form-control" readonly />
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="BirthPlace.Region" class="control-label">Birth Region</label>
                    <input asp-for="BirthPlace.Region" class="form-control" readonly />
                </div>
                <div class="col-md-4 mb-4">
                    <label asp-for="BirthPlace.City" class="control-label">Birth City</label>
                    <input asp-for="BirthPlace.City" class="form-control" readonly />
                </div>
            </div>

            <div class="form-group">
                <a asp-action="Create" asp-controller="PersonPassports" asp-route-personId="@Model.PersonId" asp-route-returnUrl="@Context.Request.Path" class="btn btn-primary">Add Passport</a>
                <a asp-action="Index" asp-controller="People" class="btn btn-secondary">Back to Persons</a>
            </div>


        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-6 offset-md-3">
        @if (Model.PersonPassport != null)
        {
            <form asp-action="" class="shadow p-3 mb-5 bg-white rounded">
                <div class="row mb-4">
                <!-- Photograph Block -->
                <div class="col-md-6 mx-auto text-center">
                @*     <img src="" alt="Photograph" class="img-fluid bg-primary" style="max-width: 150px; height: auto;" /> *@
                    <div class="bg-secondary" style="width:150px; height: 175px;"></div>
                </div>


                <!-- Name and Surname Block -->
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12 mb-4">
                            <label asp-for="PersonName" class="control-label">Person Name</label>
                            <input asp-for="PersonName" class="form-control" readonly />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 mb-4">
                            <label asp-for="PersonSurname" class="control-label">Person Surname</label>
                            <input asp-for="PersonSurname" class="form-control" readonly />
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonPassport.Passport_Number" class="control-label">Passport Number</label>
                    <input asp-for="PersonPassport.Passport_Number" class="form-control" readonly />
                </div>

                    <div class="col-md-6 mb-4">
                        <label asp-for="PersonPassport.Authority" class="control-label">Authority</label>
                        <input asp-for="PersonPassport.Authority" class="form-control" readonly />
                    </div>
            </div>

            <!-- Additional Passport Fields -->
            <div class="row">
                <div class="col-md-6 mb-4">
                    <label asp-for="PersonPassport.Date_of_Issue" class="control-label">Date of Issue</label>
                    <input asp-for="PersonPassport.Date_of_Issue" class="form-control" readonly />
                </div>

                <div class="col-md-6 mb-4">
                    <label asp-for="PersonPassport.Date_of_Expiry" class="control-label">Date of Expiry</label>
                    <input asp-for="PersonPassport.Date_of_Expiry" class="form-control" readonly />
                </div>


                 <div class="col-md-6 mb-4 align-self-end ml-auto">
                     <a asp-action="Delete" asp-controller="PersonPassports" asp-route-id="@Model.PersonPassport.PersonPassportId" asp-route-returnUrl="@Url.Action("Details", "People", new { id = Model.PersonId })" class="btn btn-danger">Delete</a>
                 </div>

            </div>
        </form>
        }
    </div>
</div>